### ISSUE TITLE
[rcm ispconfig setup] Perlu memaksimalkan user ispconfig terutama pada nginx config.

### ISSUE THREAD

**Issue by ijortengab** [ijortengab/rcm#4]
Hasil dari menggunakan `rcm-ispconfig-setup-variation5.sh` pada PHP Versi 8.3.

Saat gagal login pada halaman login ISPConfig, muncul 500 HTTP Error.

Cek di log, hasilnya sebagai berikut:

```
tail -f /var/log/nginx/error.log
```

output:

```
2024/05/18 09:16:51 [error] 259253#259253: *1590 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: fwrite(): Argument #1 ($stream) must be of type resource, false given in /usr/local/ispconfig/interface/lib/app.inc.php:217
Stack trace:
#0 /usr/local/ispconfig/interface/lib/app.inc.php(217): fwrite()
#1 /usr/local/ispconfig/interface/web/login/index.php(180): app->auth_log()
#2 /usr/local/ispconfig/interface/web/login/index.php(459): process_login_request()
#3 {main}
  thrown in /usr/local/ispconfig/interface/lib/app.inc.php on line 217" while reading response header from upstream, client: 152.118.38.22, server: cp.systemix.id, request: "POST /login/index.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.3-fpm.sock:", host: "cp.systemix.id", referrer: "https://cp.systemix.id/login/"
```

Cek pada code, disimpulkan bahwa user web server `www-data` conflict dengan `ispconfig`.

```
root@server:/etc/nginx/sites-available# ls -la /var/log/ispconfig/auth.log
-rw-rw---- 1 ispconfig ispconfig 0 May 18 06:11 /var/log/ispconfig/auth.log
```

Sementara saat instalasi, terdapat chown sebagai berikut:

(File install/lib/installer_base.lib.php line 3843)

```
exec('chown ispconfig:ispconfig '. $conf['ispconfig_log_dir'].'/auth.log');
```

Solusi sementara:

- [x] `cd /var/log/ispconfig; chown www-data:www-data auth.log`

Solusi jangka panjang: maksimalkan user ispconfig yang exists, baik di web server, maupun php cgi.

## Todo
 - [x] Instaler 
Hapus code berikut pada file `rcm-ispconfig-autoinstaller-nginx.sh`:
```
    __ Mengubah kepemilikan directory '`'ISPConfig'`'.
    __; magenta chown -R $user_nginx:$user_nginx /usr/local/ispconfig; _.
    chown -R $user_nginx:$user_nginx /usr/local/ispconfig
```

- [x] PHP FPM

Pastikan tidak lagi website ISPConfig menggunakan PHP-FPM dari www-data, cek di: /etc/php/8.2/fpm/pool.d/ispconfig.conf

**Comment by ijortengab** [comment]
Semua command ISPConfig pindah ke repository mandiri: https://github.com/ijortengab/ispconfig-autoinstaller.
Issue sudah di fix pada commit sbb: https://github.com/ijortengab/ispconfig-autoinstaller/commit/fbe1feb6a5897d396cb76ac173e9a06c06dc89e6#diff-229fab563b19571fa5310b798d1dbacc3afc65a3dade4b1f153a9f1edb8a06f9L779
